### ISSUE TITLE
Feature Request: Reuse chromedriver across different test files.

### ISSUE THREAD

**Issue by mctrafik** [erwinheitzman/jest-webdriverio-standalone-boilerplate#6]
If I read this code correctly, it runs webdriver setup and teardown for every test file. This creates a slowdown in execution time. Anecdotally I see a 5 second setup time per file.

I'm not sure how to address that though. Can you add a second test file and see how they execute?

**Comment by erwinheitzman** [comment]
Since the ChromeDriver handles the instances internally that is possible yes. If this was setup with the GeckoDriver however it should be as it is right now.
I'll fix this when I got the time 👍

**Comment by erwinheitzman** [comment]
@mctrafik I have just pushed an update containing typescript and a more flexible setup that fixes the issue you mentioned.

Try it out and let me know!
